SELECT
    o.order_id,
    o.order_no,
    o.order_type_code,
    o.order_status_code,
    o.customer_address_id,
    o.customer_name,
    o.order_date,
    o.delivery_date,
    o.valid_until,
    o.reference_text,
    o.external_reference,
    o.language_code,
    o.currency_code,
    o.payment_term_code,
    o.vat_mode,
    o.header_discount_type,
    o.header_discount_value,
    o.header_discount_amount,
    o.header_surcharge_type,
    o.header_surcharge_value,
    o.header_surcharge_amount,
    o.subtotal_net_amount,
    o.net_amount,
    o.vat_amount,
    o.gross_amount,
    o.notes_text,
    o.internal_notes_text,
    o.result_document_id,
    a.company_name,
    a.first_name,
    a.last_name
FROM
    ord_order AS o
    LEFT JOIN adr_address AS a
        ON o.customer_address_id = a.address_id;
